const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const configPath = path.join(__dirname, 'config.js');
const examplePath = path.join(__dirname, 'config.example.js');

let backendUrl;

if (fs.existsSync(envPath)) {
  require('dotenv').config({ path: envPath });
  backendUrl = process.env.BE_URL;
}

if (!backendUrl) {
  if (fs.existsSync(envPath)) {
    console.warn('Warning: BE_URL missing in .env; using placeholder (OCR backend URL).');
  } else {
    console.warn('No .env file; using placeholder for config.js. Copy .env from config.example or add BE_URL when using cloud OCR.');
  }
  backendUrl = 'YOUR_BACKEND_URL_HERE';
}

const content = `// Auto-generated by build-config.js (from .env when present)
export const BACKEND_URL = ${JSON.stringify(backendUrl)};
`;

fs.writeFileSync(configPath, content);
console.log(`Wrote config.js with BACKEND_URL=${backendUrl === 'YOUR_BACKEND_URL_HERE' ? '(placeholder)' : backendUrl}`);
